#!/bin/bash

# Fetch kernel args and cut off everything except first argument
# Which must be warg=VAL
wArg="$(/bin/cat /proc/cmdline)"
wArg=${wArg%% *}

if [[ "${wArg%%=*}" != "warg" ]]; then
    echo "First boot parameter is ${wArg%%=*}, but expected warg!"
    /sbin/reboot
fi

#Get the actual value VAL of "warg=VAL"
wArg="${wArg##*=}"

#The workloadName is determined by the runlevel
workLoadName="$(/bin/rc-status -r)"

TIMEFORMAT="%3R"
#Print execution time of this workload, dump the regular output
etime=$( { time $workLoadName $wArg; }  2>&1 > /dev/null )
#Print the runtime as ms (without the dot, e.g. 0.15 to 015)
echo "WORKLOADRUNTIME ${etime//./}"

#Reboot (kill the VM)
/sbin/reboot